#!/usr/bin/env sh

set -e
set -x

if [ "$1" = "--testing" ]; then
  export UCS_REPOS="testing"
else
  export UCS_REPOS="stable"
fi

if [ "$1" = "--ucsschool" ] || [ "$2" = "--ucsschool" ]; then
  export UCSSCHOOL=1
  echo "Building with UCS@school app installed."
else
  export UCSSCHOOL=0
  echo "Building without UCS@school app."
fi

. ./common.sh

if ! docker images "${DOCKER_REGISTRY}/${UDM_ONLY_PARENT_DOCKER_IMG}:${UCS_REPOS}-${UCS_VERSION}" | grep -E -q -v '^REPOSITORY'; then
  echo "Please build '$UDM_ONLY_PARENT_DOCKER_IMG' image first, running ./build_ucs_join_image.sh $1"
  exit 1
fi

echo "Building image '$UDM_ONLY_TARGET_DOCKER_IMG_VERSION'..."
docker build \
  -f ./Dockerfile.udm_rest_api_only \
  -t "$UDM_ONLY_TARGET_DOCKER_IMG_VERSION" \
  --build-arg DOCKER_REGISTRY="$DOCKER_REGISTRY" \
  --build-arg UDM_ONLY_PARENT_DOCKER_IMG="$UDM_ONLY_PARENT_DOCKER_IMG" \
  --build-arg UCS_REPOS="$UCS_REPOS" \
  --build-arg UCS_VERSION="$UCS_VERSION" \
  . || exit 1

echo "Tagging new image as latest..."
docker tag "$UDM_ONLY_TARGET_DOCKER_IMG_VERSION" "$UDM_ONLY_TARGET_DOCKER_IMG_LATEST"
