version: '2'

services:
    ucs:
        build:
            dockerfile: Dockerfile.${UCS_REPOS}
            context: .
            args:
                - DOCKER_REGISTRY=${DOCKER_REGISTRY}
                - UCS_VERSION=${UCS_VERSION}
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        environment:
            - container=docker
            - domainname=ucs-test.intranet
            - rootpwd=univention
        tmpfs:
            - /run
            - /run/lock
        cap_add:
            - SYS_ADMIN
        privileged: true
        ports:
          - 9080:80/tcp
          - 9443:443/tcp
        hostname: master
        command: /sbin/init
