# This workflow will install Python dependencies and run integration tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install pytest-cov
        python -m pip install -r requirements.txt -r requirements_dev.txt -r requirements_test.txt
        python -m pip list
    - name: Install Python package
      run: python -m pip install -e .
    - name: start docker container
      run: make start-docker-container
    - name: install OpenAPI client
      run: make pip-install-openapi-client-from-test-pypi
    - name: Test with pytest
      run: pytest -l -v --cov=tests --cov=udm_rest_client --cov-fail-under=100 --cov-report=term-missing
