# This workflow will install Python dependencies and run integration tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration tests

on: [ push, pull_request ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python3 -m pip install --upgrade pip wheel
                    python3 -m pip install pytest-cov
                    python3 -m pip install -r requirements.txt -r requirements_dev.txt -r requirements_test.txt
                    python3 -m pip list
            -   name: Install Python package
                run: python3 -m pip install -e .
            -   name: Install yq
                run: |
                    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
                    sudo add-apt-repository --yes ppa:rmescandon/yq
                    sudo apt update
                    sudo apt install --yes yq
            -   name: Update LXD
                run: |
                    sudo snap list
                    sudo snap refresh
                    sudo snap refresh --channel=latest lxd
                    sudo snap list
            -   name: Start LXD container
                run: |
                    sudo lxd init --auto --storage-backend dir
                    make download-lxc-container
                    sudo make create-lxd-test-server-config
            -   name: Install OpenAPI client
                run: UCS_HOST=$(sudo sh -c ". $PWD/lxd.sh; lxd_container_ip") make pip-install-openapi-client
            -   name: Test with pytest
                run: pytest -l -v --cov=tests --cov=udm_rest_client --cov-fail-under=100 --cov-report=term-missing
